### ISSUE TITLE
А как должен выглядеть settings.py?

### ISSUE THREAD

**Issue by artembaechka** [nickname123456/netschool#1]
А как должен выглядеть settings.py? Буду признателен если зальете settings.py в виде файла

**Comment by artembaechka** [comment]
Кстати хороший скам на данные с сетевого города

**Comment by nickname123456** [comment]
> А как должен выглядеть settings.py? Буду признателен если зальете settings.py в виде файла

![image](https://user-images.githubusercontent.com/71244456/166095194-efe78779-92a5-4ded-83c9-930eb9d61858.png)

**Comment by kirillarz** [comment]
> А как должен выглядеть settings.py? Буду признателен если зальете settings.py в виде файла

Файлом не смог

```Python
token = 'ТОКЕН ВК ГРУППЫ'

admin_login = 'логин СГО'
admin_password = 'пароль СГО'
admin_school = 'полное название школы'
admin_link = 'ссылка на СГО'
admin_id = 'ВК id админа'

lessons_and_their_reduction = {
    'Информатика': 'Инф.',
    'Алгебра': 'Алгебра',
    'Химия': 'Химия',
    'Физика': 'Физика',
    'География': 'Геогр.',
    'Биология': 'Биол.',
    'Геометрия': 'Геом.',
    'Физическая культура': 'Физ-ра',
    'Основы безопасности жизнедеятельности': 'ОБЖ',
    'Музыка': 'Музыка',
    'Обществознание': 'Общество.',
    'История': 'История',
    'Родной русский язык 5-11': 'Родн.Рус. яз.',
    'Родная (русская) литература 5-9': 'Родн. лит-ра',
    'Иностранный язык (англ.язык)': 'Англ. яз.',
    'Технология': 'Техн.',
    'Русский язык': 'Рус. яз.',
    'Литература.': 'Литература',
}
```

**Comment by kirillarz** [comment]
> Кстати хороший скам на данные с сетевого города

![image](https://user-images.githubusercontent.com/71244456/166096847-8a4da6ff-ea0d-4625-bb04-410eb991288e.png)
